### ISSUE TITLE
command processor

### ISSUE THREAD

**Issue by py2100** [MagnusStarkadOttosen/CDIO#3]
Take C# code from UnitySim branch, lav om til python, have server respond to client when it has executed command

**Comment by hellomelissaw** [comment]
Have set up basis code, need to make server respond to client when done executing command

**Comment by hellomelissaw** [comment]
Have set up a basic mechanism where client sends command and waits for server response in a loop,

TO DO : needs additional mechanism to stop the client command loop if robot needs to be stopped (for example if about to hit obstacle)

**Comment by hellomelissaw** [comment]
task transfered to "adding command options" and "adding command queue", will close this issue now
